site_name: Paint Robot
site_description: A Python-based research and implementation project for paint robot control and optimization
site_author: Simon
site_url: https://SimonMeersschaut.github.io/paint-bot/

theme:
  name: readthedocs
  palette:
    - scheme: default
      primary: blue
      accent: orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tasklist
  - attr_list
  - tables
  - admonition
  - toc

# This section hooks up the MathJax scripts required to convert your LaTeX syntax into visual math on the page
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Contributing: contributing.md
  - License: license.md
  - Stroke Generation Algorithm:
    - Overview: stroke_algorithm/overview.md
    - Stroke Ordering: stroke_algorithm/stroke_ordering.md
    - Expanding: stroke_algorithm/stroke_expanding.md
    - Supervisor: stroke_algorithm/supervisor.md
  - Hardware:
    - Overview: hardware/overview.md
    - 3D Prints: hardware/3d_prints.md
  - API Reference:
    - Datatypes: api/datatypes.md
    - StrokeSequence: api/strokesequence.md
    - StrokePath: api/strokepath.md
    - RobotCalibration: api/calibration.md

docs_dir: docs
site_dir: site